# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
encoding: utf-8
lang: en-US
url: 'https://christinageorgeart.com'
baseurl: ''
title: 'Christina George, artist'
description: 'Christina George artist portfolio'
logo: Christina George
email: "christinajoy.george@gmail.com"

# Jekyll Settings
sass:
  style: compressed
css_inline: true
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: "#about"
- title: Portfolio
  url: /portfolio

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
- title: Created by Garrett George

# Collections
collections:
  works:
    title: Portfolio
    output: true
    description: "Paintings and drawings"
    feature_text: |
      Portfolio

  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Defaults
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
