# Set theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# Site settings
encoding: utf-8
lang: en-US
url: 'https://christinageorgeart.com'
baseurl: ''
title: 'Christina George, artist'
description: 'Christina George artist portfolio'
logo: 'Christina George'
email: "christinajoy.george@gmail.com"
sitemap: true

# Jekyll Settings
sass:
  style: compressed
css_inline: true
permalink: pretty

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  blanklines: false # boolean - strip blank lines and breaks
  #profile: true # boolean - print table of data saved
  #ignore:
  #envs: [local]

# Pagination
paginate: 5
paginate_path: blog/page:num

# Content
asset_serve_path: "/assets/" 
image_serve_path: "/assets/images/" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Collections
collections:
  works:
    title: Portfolio
    output: true
    description: "Paintings and drawings"
    feature_text: |
      Portfolio
    order:
      - inhale.md
      - kindred-spirits.md
      - february-ink-sketch.md
      - february-ink-wash.md
      - february.md
      - lenten-i.md
      - lenten-ii.md
      - lenten-iii.md
      - lenten-iv.md
      - lenten-v.md

  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Defaults
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
